### ISSUE TITLE
Add a CI linter

### ISSUE THREAD

**Issue by JeremyPansier** [my-cloud/ruthenium#47]
* [x] add the following job in the quality workflow:
```
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@v3
```
